FORMAT: 1A
HOST: http://smg.lileesystems.com

# SMG API
SMG API provides http interface to manipulate devices and jobs in SMG.

# Group Initialization

User must issues the following two requests to initialize API session.
SMG API use cookie as session token. The cookie must be included in every subsequent request.

## POST /login/auth.cgi
+ Request (application/x-www-form-urlencoded)

        username=admin&passwd=admin

+ Response 302

## GET /smg/api/session/init
+ Response 200 (application/json)

        {
            "component": [ "list of component" ],
            "event": { "event id": "event value" },
            "log_level": [ "list of log level" ],
            "log_type": [ "list of log type" ],
            "state": { "device state id": "device state name" },
            "status": [ "list of device status" ],
            "variables": { "status variable id": "status variable name" },
            "job_state": [ "list of job state" ],
            "command_code": [ "list of acceptable command" ],
            "mtn_code": [ "job type id": "job type name" ],
            "read_at": <system unix time>
        }


# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
